<?xml version="1.0"?>
<robot name="wchair" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find ros_ag)/urdf/w.urdf.xacro" /> 
<!-- ##################################################################### -->
	<!-- PROPERTY LIST -->
	<property name="M_PI" value="3.1415926535897931" />
	<property name="base_x" value="0.75" />
	<property name="base_y" value="0.5" />
	<property name="base_z" value="0.30" />
	<property name="base_mass" value="5.0"/>
	<property name="caster_radius" value="0.1"/>
	<property name="caster_mass" value="0.5"/>

	<property name="hokuyo_size" value="0.05"/>
	<property name="imu_size" value="0.05"/>
	
	<property name="rate_sensor" value="1.0"/>
	
<!-- ##################################################################### -->
	<!-- Base Link -->
	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
			<material name="blue"><color rgba="0 0.5 1 1"/></material>
		</visual>
		<!-- Base collision -->
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${base_x} ${base_y} ${base_z}"/></geometry>
		</collision>
		<inertial>
			<mass value="${base_mass}"/>
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyx="0.0" iyy="0.21" iyz="0.0" izx="0.0" izy="0.0" izz="0.13"/>
		</inertial>
	</link>
	<gazebo reference="base_link">
		<material>Gazebo/SkyBlue</material>
		<!-- <turnGravityOff>false</turnGravityOff> -->
	</gazebo>
<!-- ##################################################################### -->
	<!-- Caster -->
	<link name="caster_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><sphere radius="${caster_radius}" /></geometry>
			<material name="White" />
		</visual>
		<!-- Caster collision -->
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><sphere radius="${caster_radius}" /></geometry>
		</collision>
		<inertial>
			<mass value="${caster_mass}"/>
			<inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
		</inertial>
	</link>
	<joint name="caster_joint" type="continuous">
    	<parent link="base_link"/>
    	<child link="caster_link"/>
    	<origin xyz="0.25 0 -0.15" rpy="0 0 0" />
    	<axis xyz="0 0 1" />
  	</joint>
  	<gazebo reference="caster_link">
  		<material>Gazebo/Grey</material>
    	<!-- <turnGravityOff>false</turnGravityOff> -->
  	</gazebo>
<!-- ##################################################################### -->
	<!-- Wheels-->
	<wheel lr="right" parent="base_link" translateX="-0.15" translateY="-0.3" translateZ="-0.05" flipY="1" />
	<wheel lr="left" parent="base_link" translateX="-0.15" translateY="0.3" translateZ="-0.05" flipY="1" />
<!-- ################################################################## -->	
	<!-- PEDANE -->
	<link name="pedana1">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.02 0.5 0.35" /></geometry>
			<material name="Black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.02 0.5 0.35" /></geometry>
		</collision>
	</link>
	<joint name="joint_pedana1" type="fixed">
		<parent link="base_link"/>
		<child link="pedana1"/>
		<origin xyz="0.42 0 0.05" rpy="0 -0.40 0" />
	</joint>
	<gazebo reference="pedana1">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ################################################################## -->	
	<!-- PEDANA 2 -->
	<link name="pedana2">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.25 0.5 0.02" /></geometry>
			<material name="Black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.25 0.5 0.02"  /></geometry>
		</collision>
	</link>
	<joint name="joint_pedana2" type="fixed">
		<parent link="base_link"/>
		<child link="pedana2"/>
		<origin xyz="0.60 0 -0.12" rpy="0 0 0" />
	</joint>
	<gazebo reference="pedana2">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ################################################################## -->	
	<!-- SEDILE -->
	<link name="sedile">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.35 0.5 0.08" /></geometry>
			<material name="Black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.35 0.5 0.08" /></geometry>
		</collision>
	</link>
	<joint name="joint_sedile" type="fixed">
		<parent link="base_link"/>
		<child link="sedile"/>
		<origin xyz="0.19 0 0.19" rpy="0 0 0" />
	</joint>
	<gazebo reference="sedile">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ################################################################## -->	
	<!-- SCHIENALE -->
	<link name="schienale">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.06 0.5 0.48" /></geometry>
			<material name="Black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.06 0.5 0.48" /></geometry>
		</collision>
	</link>
	<joint name="joint_schienale" type="fixed">
		<parent link="base_link"/>
		<child link="schienale"/>
		<origin xyz="0 0 0.45" rpy="0 -0.2 0" />
	</joint>
	<gazebo reference="schienale">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ################################################################## -->	
	<!-- BRACCIOLO DX-->
	<link name="bracciolo_dx">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
			<material name="Black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
		</collision>
	</link>
	<joint name="joint_bracciolo_dx" type="fixed">
		<parent link="base_link"/>
		<child link="bracciolo_dx"/>
		<origin xyz="0.16 -0.28 0.4" rpy="0 0 0" />
	</joint>
	<gazebo reference="bracciolo_dx">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ################################################################## -->	
	<!-- BRACCIOLO SX-->
	<link name="bracciolo_sx">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
			<material name="Black"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="0.40 0.06 0.04" /></geometry>
		</collision>
	</link>
	<joint name="joint_bracciolo_sx" type="fixed">
		<parent link="base_link"/>
		<child link="bracciolo_sx"/>
		<origin xyz="0.16 0.28 0.4" rpy="0 0 0" />
	</joint>
	<gazebo reference="bracciolo_sx">
  		<material>Gazebo/DarkGrey</material>
  	</gazebo>
<!-- ##################################################################### -->
	<!-- SENSORS -->  
	<!-- hokuyo -->
	<link name="hokuyo_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry><box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/></geometry>
			<material name="Black" />
		</visual>
	</link> 
	<joint name="hokuyo_joint" type="fixed">
		<origin xyz="0.7 0 -0.085" rpy="0 0 0" />
		<parent link="base_link"/>
		<child link="hokuyo_link" />
	</joint>
	<gazebo reference="hokuyo_link">
		<material>Gazebo/Black</material>
		<!-- <turnGravityOff>false</turnGravityOff> -->
		<sensor type="ray" name="head_hokuyo_sensor">
			<pose>${hokuyo_size/2} 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>${rate_sensor}</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>720</samples>
						<resolution>1</resolution>
						<min_angle>-1.570796</min_angle>
						<max_angle>1.570796</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.10</min>
					<max>10.0</max>
					<resolution>0.001</resolution>
				</range>
			</ray>
			<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
				<topicName>/scan</topicName>
				<frameName>hokuyo_link</frameName>
			</plugin>
		</sensor>
	</gazebo>
	
<!-- ##################################################################### -->
	<!-- SENSORS imu -->	
	<link name="imu_link">
  		<visual>
    		<origin rpy="0 0 0" xyz="0 0 0"/>
      		<geometry><box size="0.05 0.05 0.05"/></geometry>
			<material name="Orange" />
  		</visual>
	</link>
	<joint name="imu_joint" type="fixed">
    	<origin xyz="${-base_x/2 + hokuyo_size} 0 ${base_z/2+hokuyo_size/2}"/>
    	<parent link="base_link"/>
    	<child link="imu_link"/>
  	</joint>
	<gazebo reference="imu_link">
		<material>Gazebo/Orange</material>
		<!-- <turnGravityOff>false</turnGravityOff> -->
		<sensor name="imu_sensor" type="imu">
			<imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
			<pose>0 0 0 0 0 0</pose>
			<update_rate>${rate_sensor}</update_rate>
    		<plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so"> 
    	  		<topicName>/imu</topicName>
    	  		<frameName>imu_link</frameName>
    	  		<!--<alwaysOn>true</alwaysOn>
    	  		<bodyName>base_link</bodyName>
    	  		<gaussianNoise>0.0</gaussianNoise> 
    	  		<serviceName>imu/calibrate</serviceName>
    	  		<rpyOffset>0 0 0</rpyOffset> 
				<accelDrift>0.5 0.5 0.5</accelDrift>
				<accelGaussianNoise>0.35 0.35 0.3</accelGaussianNoise>
				<rateDrift>0.1 0.1 0.1</rateDrift>
				<rateGaussianNoise>0.05 0.05 0.015</rateGaussianNoise>-->
    		</plugin>
    	</sensor> 
  	</gazebo>
<!-- ##################################################################### -->	
	<!-- Differential drive controller  -->
	<!-- Per muove il robot in Gazebo dobbiamo aggiungere questo plugin "libgazebo_ros_diff_drive.so" -->
	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<rosDebugLevel>Debug</rosDebugLevel>
			<publishWheelTF>false</publishWheelTF>
			<robotNamespace>/</robotNamespace>
			<publishTf>1</publishTf>
			<publishWheelJointState>false</publishWheelJointState>
			<alwaysOn>true</alwaysOn>
			<updateRate>100.0</updateRate>
			<leftJoint>left_wheel_joint</leftJoint>
			<rightJoint>right_wheel_joint</rightJoint>
			<wheelSeparation>${base_y}</wheelSeparation>
			<wheelDiameter>${2*wheel_radius}</wheelDiameter>
			<broadcastTF>1</broadcastTF>
			<wheelTorque>30</wheelTorque>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic> <!-- Topic importante per per pubblicarci il messaggio di tipo Twist-->
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic> 
			<robotBaseFrame>base_link</robotBaseFrame>
		</plugin>
	</gazebo> 
</robot>

